name: Build and publish images backstage microservice demo 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: product-service/Dockerfile
            image: ghcr.io/1211/product-service
          - dockerfile: inventory-service/Dockerfile
            image: ghcr.io/1211/inventory-service
          - dockerfile: order-service/Dockerfile
            image: ghcr.io/1211/order-service
          - dockerfile: notification-service/Dockerfile
            image: ghcr.io/1211/notification-service
          - dockerfile: discovery-service/Dockerfile
            image: ghcr.io/1211/discovery-service
          - dockerfile: api-gateway/Dockerfile
            image: ghcr.io/1211/api-gateway
                  
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    # - name: Build with Maven
    #   working-directory: ${{ matrix.image }}
    #   run: mvn -B package --file pom.xml
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        # registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
#    - name: Build Docker Image with Jib
#      working-directory: .
#      run: mvn clean package -P build-docker-image

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ matrix.image }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ matrix.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
