name: Build and publish images backstage microservice demo 

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        image: ["product_service", "inventory_service", "order_service", "notification_service", "discovery_service", "api-gateway"]
        
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    # - name: Build with Maven
    #   working-directory: ${{ matrix.image }}
    #   run: mvn -B package --file pom.xml
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
    - name: Build Docker Image with Jib
      run: mvn clean package -P build-docker-image

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ env.REGISTRY }}/${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.image }}::latest
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ${{ matrix.image }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
